---
title: "Lab Exercise 1"
output:
  html_document:
    df_print: paged
date: "2024-04-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


CATEGORY- GAMING ACCESSORIES
1ST PRODUCT - MONITOR
```{r}

library(rvest)
library(dplyr)
library(polite)
library(httr)


GamingAccessories <- data.frame()

url <- "https://www.amazon.co.uk/s?bbn=428652031&rh=n%3A428652031%2Cp_n_feature_eighteen_browse-bin%3A65675343031&dc&qid=1707357020&rnid=65675330031&ref=lp_428652031_nr_p_n_feature_eighteen_browse-bin_3"

session <- bow(url,user_agent = "For Educational Purposes")

amazon <- read_html(url)

Category <- "GamingAccessories"

monitor <- scrape(session) %>%
  html_nodes("span.a-text-normal") %>%
  html_text
monitor24 <- monitor[1:24]
monitor24


monitor_prices <- scrape(session) %>%
  html_nodes("span.a-price-whole") %>%
  html_text
monitor_prices24 <-monitor_prices[1:24]
monitor_prices24


monitor_Ratings <- scrape(session) %>%
  html_nodes("i.a-icon.a-icon-star-small.a-star-small-4.aok-align-bottom") %>%
  html_text
monitor_Ratings24 <-monitor_Ratings[1:24]
monitor_Ratings24


monitor_noReviews <- scrape(session) %>%
  html_nodes("span.a-size-base.s-underline-text") %>%
  html_text
monitor_noReviews24 <-monitor_noReviews[1:24]
monitor_noReviews

GamingAccessories <-data.frame(category = Category,
                               name = monitor24,
                               price = monitor_prices24,
                               ratings = monitor_Ratings24,
                               no_of_reviews = monitor_noReviews)


url2 <- "https://www.amazon.co.uk/s?i=computers&bbn=428652031&rh=n%3A428652031%2Cp_n_feature_eighteen_browse-bin%3A65675343031&dc&page=2&qid=1707649175&rnid=65675330031&ref=sr_pg_2"

session2 <- bow(url2,user_agent = "For Educational Purposes")

amazon <- read_html(url)

Category <- "GamingAccessories"

page2_monitor <- scrape(session2) %>%
  html_nodes("span.a-text-normal") %>%
  html_text
page2_monitor24 <- page2_monitor[1:24]
page2_monitor24


page2_monitor_prices <- scrape(session2) %>%
  html_nodes("span.a-price-whole") %>%
  html_text
page2_monitor_prices24 <-page2_monitor_prices[1:24]
page2_monitor_prices24


page2_monitor_Ratings <- scrape(session2) %>%
  html_nodes("i.a-icon.a-icon-star-small.a-star-small-4.aok-align-bottom") %>%
  html_text
page2_monitor_Ratings24 <-page2_monitor_Ratings[1:24]
page2_monitor_Ratings24


page2_monitor_noReviews <- scrape(session2) %>%
  html_nodes("span.a-size-base.s-underline-text") %>%
  html_text
page2_monitor_noReviews24 <-page2_monitor_noReviews[1:24]
page2_monitor_noReviews

GamingAccessories <-  rbind(GamingAccessories,data.frame(category = Category,
                               name = page2_monitor24,
                               price = page2_monitor_prices24,
                               ratings = page2_monitor_Ratings24,
                               no_of_reviews = page2_monitor_noReviews))



url3 <- "https://www.amazon.co.uk/s?i=computers&bbn=428652031&rh=n%3A428652031%2Cp_n_feature_eighteen_browse-bin%3A65675343031&dc&page=3&qid=1707650116&rnid=65675330031&ref=sr_pg_3"

session3 <- bow(url3,user_agent = "For Educational Purposes")

amazon <- read_html(url)

Category <- "GamingAccessories"

page3_monitor <- scrape(session3) %>%
  html_nodes("span.a-text-normal") %>%
  html_text
page3_monitor24 <- page3_monitor[1:24]
page3_monitor24


page3_monitor_prices <- scrape(session3) %>%
  html_nodes("span.a-price-whole") %>%
  html_text
page3_monitor_prices24 <-page3_monitor_prices[1:24]
page3_monitor_prices24


page3_monitor_Ratings <- scrape(session3) %>%
  html_nodes("i.a-icon.a-icon-star-small.a-star-small-4.aok-align-bottom") %>%
  html_text
page3_monitor_Ratings24 <-page3_monitor_Ratings[1:24]
page3_monitor_Ratings24


page3_monitor_noReviews <- scrape(session3) %>%
  html_nodes("span.a-size-base.s-underline-text") %>%
  html_text
page3_monitor_noReviews24 <-page3_monitor_noReviews[1:24]
page3_monitor_noReviews24

GamingAccessories <- rbind(GamingAccessories,data.frame(category = Category,
                               name = page3_monitor24,
                               price = page3_monitor_prices24,
                               ratings = page3_monitor_Ratings24,
                               no_of_reviews = page3_monitor_noReviews24))


url4 <- "https://www.amazon.co.uk/s?i=computers&bbn=428652031&rh=n%3A428652031%2Cp_n_feature_eighteen_browse-bin%3A65675343031&dc&page=4&qid=1707650974&rnid=65675330031&ref=sr_pg_4"

session4 <- bow(url4,user_agent = "For Educational Purposes")

amazon <- read_html(url)

Category <- "GamingAccessories"

page4_monitor <- scrape(session4) %>%
  html_nodes("span.a-text-normal") %>%
  html_text
page4_monitor24 <- page4_monitor[1:24]
page4_monitor24


page4_monitor_prices <- scrape(session4) %>%
  html_nodes("span.a-price-whole") %>%
  html_text
page4_monitor_prices24 <-page4_monitor_prices[1:24]
page4_monitor_prices24


page4_monitor_Ratings <- scrape(session4) %>%
  html_nodes("i.a-icon.a-icon-star-small.a-star-small-4.aok-align-bottom") %>%
  html_text
page4_monitor_Ratings24 <-page4_monitor_Ratings[1:24]
page4_monitor_Ratings24


page4_monitor_noReviews <- scrape(session4) %>%
  html_nodes("span.a-size-base.s-underline-text") %>%
  html_text
page4_monitor_noReviews24 <-page4_monitor_noReviews[1:24]
page4_monitor_noReviews24

GamingAccessories <- rbind(GamingAccessories,data.frame(category = Category,
                               name = page4_monitor24,
                               price = page4_monitor_prices24,
                               ratings = page4_monitor_Ratings24,
                               no_of_reviews = page4_monitor_noReviews24))


url5 <- "https://www.amazon.co.uk/s?i=computers&bbn=428652031&rh=n%3A428652031%2Cp_n_feature_eighteen_browse-bin%3A65675343031&dc&page=4&qid=1707650974&rnid=65675330031&ref=sr_pg_5"

session5 <- bow(url5,user_agent = "For Educational Purposes")

amazon <- read_html(url)

Category <- "GamingAccessories"

page5_monitor <- scrape(session5) %>%
  html_nodes("span.a-text-normal") %>%
  html_text
page5_monitor24 <- page5_monitor[1:24]
page5_monitor24


page5_monitor_prices <- scrape(session5) %>%
  html_nodes("span.a-price-whole") %>%
  html_text
page5_monitor_prices24 <-page5_monitor_prices[1:24]
page5_monitor_prices24


page5_monitor_Ratings <- scrape(session5) %>%
  html_nodes("i.a-icon.a-icon-star-small.a-star-small-4.aok-align-bottom") %>%
  html_text
page5_monitor_Ratings24 <-page5_monitor_Ratings[1:24]
page5_monitor_Ratings24


page5_monitor_noReviews <- scrape(session5) %>%
  html_nodes("span.a-size-base.s-underline-text") %>%
  html_text
page5_monitor_noReviews24 <-page5_monitor_noReviews[1:24]
page5_monitor_noReviews24

GamingAccessories <- rbind(GamingAccessories,data.frame(category = Category,
                               name = page5_monitor24,
                               price = page5_monitor_prices24,
                               ratings = page5_monitor_Ratings24,
                               no_of_reviews = page5_monitor_noReviews24))

url6 <- "https://www.amazon.co.uk/s?i=computers&bbn=428652031&rh=n%3A428652031%2Cp_n_feature_eighteen_browse-bin%3A65675343031&dc&page=4&qid=1707650974&rnid=65675330031&ref=sr_pg_6"

session6  <- bow(url6,user_agent = "For Educational Purposes")

amazon <- read_html(url)

Category <- "GamingAccessories"

page6_monitor <- scrape(session6) %>%
  html_nodes("span.a-text-normal") %>%
  html_text
page6_monitor24 <- page6_monitor[1:24]
page6_monitor24


page6_monitor_prices <- scrape(session6) %>%
  html_nodes("span.a-price-whole") %>%
  html_text
page6_monitor_prices24 <-page6_monitor_prices[1:24]
page6_monitor_prices24


page6_monitor_Ratings <- scrape(session6) %>%
  html_nodes("i.a-icon.a-icon-star-small.a-star-small-4.aok-align-bottom") %>%
  html_text
page6_monitor_Ratings24 <-page6_monitor_Ratings[1:24]
page6_monitor_Ratings24


page6_monitor_noReviews <- scrape(session6) %>%
  html_nodes("span.a-size-base.s-underline-text") %>%
  html_text
page6_monitor_noReviews24 <-page6_monitor_noReviews[1:24]
page6_monitor_noReviews24

GamingAccessories <- rbind(GamingAccessories,data.frame(category = Category,
                               name = page6_monitor24,
                               price = page6_monitor_prices24,
                               ratings = page6_monitor_Ratings24,
                               no_of_reviews = page6_monitor_noReviews24))

GamingAccessories <- GamingAccessories[1:100,]


GamingAccessories

```

```{r}
GamingAccessories <- rbind(GamingAccessories[1:100,])

GamingAccessories

write.csv(GamingAccessories,"GAMING ACCESSORIES-MONITOR.csv")


```



CATEGORY- GAMING ACCESSORIES
2ND PRODUCT - MOUSE

```{r}

GamingAccessories2 <- data.frame()

second_url <- "https://www.amazon.co.uk/s?k=gaming+mouse&crid=OGGBJVTNK196&sprefix=gaming+m%2Caps%2C510&ref=nb_sb_noss_2"

session1 <- bow(second_url,user_agent = "For Educational Purposes")

amazon <- read_html(second_url)

Category <- "GamingAccessories2"


mouse <- scrape(session1) %>%
  html_nodes("span.a-text-normal") %>%
  html_text
mouse16 <- mouse[1:16]
mouse16


mouse_prices <- scrape(session1) %>%
  html_nodes("span.a-price-whole") %>%
  html_text
mouse_prices16 <-mouse_prices[1:16]
mouse_prices16


mouse_Ratings <- scrape(session1) %>%
  html_nodes("i.a-icon.a-icon-star-small.a-star-small-4.aok-align-bottom") %>%
  html_text
mouse_Ratings16 <-mouse_Ratings[1:16]
mouse_Ratings16



mouse_noReviews <- scrape(session1) %>%
  html_nodes("span.a-size-base.s-underline-text") %>%
  html_text
mouse_noReviews16 <-mouse_noReviews[1:16]
mouse_noReviews16

GamingAccessories2 <- data.frame(category = Category,
                               name = mouse16,
                               price = mouse_prices16,
                               ratings = mouse_Ratings16,
                               no_of_reviews = mouse_noReviews16)



second_url2 <- "https://www.amazon.co.uk/s?k=gaming+mouse&page=2&crid=OGGBJVTNK196&qid=1707656950&sprefix=gaming+m%2Caps%2C510&ref=sr_pg_2"

session2 <- bow(second_url2,user_agent = "For Educational Purposes")

amazon <- read_html(second_url2)

Category <- "GamingAccessories2"


page2_mouse <- scrape(session2) %>%
  html_nodes("span.a-text-normal") %>%
  html_text
page2_mouse16 <- page2_mouse[1:16]
page2_mouse16


page2_mouse_prices <- scrape(session2)%>%
  html_nodes("span.a-price-whole") %>%
  html_text
page2_mouse_prices16 <-page2_mouse_prices[1:16]
page2_mouse_prices16


page2_mouse_Ratings <- scrape(session2)%>%
  html_nodes("i.a-icon.a-icon-star-small.a-star-small-4.aok-align-bottom") %>%
  html_text
page2_mouse_Ratings16 <-page2_mouse_Ratings[1:16]
page2_mouse_Ratings16



page2_mouse_noReviews <- scrape(session2)%>%
  html_nodes("span.a-size-base.s-underline-text") %>%
  html_text
page2_mouse_noReviews16 <-page2_mouse_noReviews[1:16]
page2_mouse_noReviews16

GamingAccessories2 <- rbind(GamingAccessories2,data.frame(category = Category,
                               name = page2_mouse16,
                               price = page2_mouse_prices16,
                               ratings = page2_mouse_Ratings16,
                               no_of_reviews = page2_mouse_noReviews16))


second_url3 <- "https://www.amazon.co.uk/s?k=gaming+mouse&page=2&crid=OGGBJVTNK196&qid=1707656950&sprefix=gaming+m%2Caps%2C510&ref=sr_pg_3"

session3 <- bow(second_url3,user_agent = "For Educational Purposes")

amazon <- read_html(second_url3)

Category <- "GamingAccessories2"


page3_mouse <- scrape(session3) %>%
  html_nodes("span.a-text-normal") %>%
  html_text
page3_mouse16 <- page3_mouse[1:16]
page3_mouse16


page3_mouse_prices <- scrape(session3)%>%
  html_nodes("span.a-price-whole") %>%
  html_text
page3_mouse_prices16 <-page3_mouse_prices[1:16]
page3_mouse_prices16


page3_mouse_Ratings <- scrape(session3)%>%
  html_nodes("i.a-icon.a-icon-star-small.a-star-small-4.aok-align-bottom") %>%
  html_text
page3_mouse_Ratings16 <-page3_mouse_Ratings[1:16]
page3_mouse_Ratings16



page3_mouse_noReviews <- scrape(session3)%>%
  html_nodes("span.a-size-base.s-underline-text") %>%
  html_text
page3_mouse_noReviews16 <-page3_mouse_noReviews[1:16]
page3_mouse_noReviews16

GamingAccessories2 <- rbind(GamingAccessories2,data.frame(category = Category,
                               name = page3_mouse16,
                               price = page3_mouse_prices16,
                               ratings = page3_mouse_Ratings16,
                               no_of_reviews = page3_mouse_noReviews16))

second_url4 <- "https://www.amazon.co.uk/s?k=gaming+mouse&page=4&crid=OGGBJVTNK196&qid=1707657955&sprefix=gaming+m%2Caps%2C510&ref=sr_pg_4"

session4 <- bow(second_url4,user_agent = "For Educational Purposes")
session4

amazon <- read_html(second_url4)

Category <- "GamingAccessories2"


page4_mouse <- scrape(session4) %>%
  html_nodes("span.a-text-normal") %>%
  html_text
page4_mouse16 <- page4_mouse[1:16]
page4_mouse16


page4_mouse_prices <- scrape(session4)%>%
  html_nodes("span.a-price-whole") %>%
  html_text
page4_mouse_prices16 <-page4_mouse_prices[1:16]
page4_mouse_prices16


page4_mouse_Ratings <- scrape(session4)%>%
  html_nodes("i.a-icon.a-icon-star-small.a-star-small-4.aok-align-bottom") %>%
  html_text
page4_mouse_Ratings16 <-page4_mouse_Ratings[1:16]
page4_mouse_Ratings16



page4_mouse_noReviews <- scrape(session4)%>%
  html_nodes("span.a-size-base.s-underline-text") %>%
  html_text
page4_mouse_noReviews16 <-page4_mouse_noReviews[1:16]
page4_mouse_noReviews16

GamingAccessories2 <- rbind(GamingAccessories2,data.frame(category = Category,
                               name = page4_mouse16,
                               price = page4_mouse_prices16,
                               ratings = page4_mouse_Ratings16,
                               no_of_reviews = page4_mouse_noReviews16))

GamingAccessories2 <- GamingAccessories2[1:100,]


GamingAccessories2


```

```{r}
GamingAccessories2 <- rbind(GamingAccessories2[1:100,])

GamingAccessories2

write.csv(GamingAccessories2,"GAMING ACCESSORIES-MOUSE.csv")


```


COMIBINED DATAFRAME OF 1ST AND 2ND PRODUCT
```{r}

scraped_products <- rbind(GamingAccessories, GamingAccessories2)
scraped_products

```

```{r}
combineprod <- rbind(scraped_products[1:100,])

combineprod

write.csv(scraped_products,"MOUSE & MONITORcombine.csv")


```





###################################################################################################



SELECT 10 PRODUCTS

```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product1 <- data.frame()

Category <- "GamingMouse"

linkRev1 <- "https://www.amazon.co.uk/AmazonBasics-Ergonomic-Wireless-Mouse-adjustable/product-reviews/B0787D6SGQ/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews"


sessionProd1 <- bow(linkRev1, user_agent = "For Educational Purpose")

scrapeNodes <- function(selector) {
  nodes <- scrape(sessionProd1) %>%
    html_nodes(selector) %>%
    html_text(trim = TRUE)
  
  if (length(nodes) == 0) {
    warning("No data found for selector: ", selector)
    return(NA)
  } else {
    return(nodes)
  }
}

  ProductName <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  Reviewer <- scrapeNodes("span.a-profile-name")[1:10]
  Review <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  Date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  ProductRating <- scrapeNodes("span.a-icon-alt")[1:10]

  product1 <- data.frame(
   category = rep(Category, length(Reviewer)),
    name = ProductName,
    reviewer = Reviewer,
    review = Review,
    date = Date,
    ratings = ProductRating
  )
  
  product1
  
linkRev2 = "https://www.amazon.co.uk/AmazonBasics-Ergonomic-Wireless-Mouse-adjustable/product-reviews/B0787D6SGQ/ref=cm_cr_getr_d_paging_btm_prev_2?ie=UTF8&reviewerType=all_reviews&pageNumber=2"
  
  sessionProd2 <- bow(linkRev2,
               user_agent = "For Educational Purpose")


      Reviewer2 <- scrapeNodes("span.a-profile-name")
      Reviewer2 <- Reviewer2[1:10]
      
      Review2 <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      Review2 <- Review2[1:10]
      
      Date2 <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      Date2 <- Date2[1:10]

      ProductRating2 <- scrapeNodes("span.a-icon-alt")
      ProductRating2 <- ProductRating2[1:10]

      
      product1 <- rbind(product1, data.frame(category = Category ,name = ProductName,
                          reviewer = Reviewer2,
                          review = Review2,
                          date = Date2,
                         ratings = ProductRating2))
      
      product1
      
      linkRev3 = "https://www.amazon.co.uk/AmazonBasics-Ergonomic-Wireless-Mouse-adjustable/product-reviews/B0787D6SGQ/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber=3"
  
  sessionProd3 <- bow(linkRev3,
               user_agent = "For Educational Purpose")


      
      Reviewer3 <- scrapeNodes("span.a-profile-name")
      Reviewer3 <- Reviewer3[1:10]

      
      Review3 <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      Review3 <- Review3[1:10]

      
      Date3 <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      Date3 <- Date3[1:10]

      
      ProductRating3 <- scrapeNodes("span.a-icon-alt")
      ProductRating3 <-  ProductRating3[1:10]

      
      product1 <- rbind(product1, data.frame(category = Category ,name = ProductName,
                          reviewer = Reviewer3,
                          review = Review3,
                          date = Date3,
                         ratings =  ProductRating3))
      
      product1 <- product1[1:25,]


      product1
      
```


```{r}


library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product2 <- data.frame()

Category <- "GamingMouse"

linkRev1 <- "https://www.amazon.co.uk/Logitech-G502-Wireless-Programmable-Next-Generation/product-reviews/B07QKC4WWD/ref=cm_cr_getr_d_paging_btm_next_3?ie=UTF8&reviewerType=all_reviews&pageNumber"


sessionProd1 <- bow(linkRev1, user_agent = "For Educational Purpose")

scrapeNodes <- function(selector) {
  nodes <- scrape(sessionProd1) %>%
    html_nodes(selector) %>%
    html_text(trim = TRUE)
  
  if (length(nodes) == 0) {
    warning("No data found for selector: ", selector)
    return(NA)
  } else {
    return(nodes)
  }
}

  ProductName <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  Reviewer <- scrapeNodes("span.a-profile-name")[1:10]
  Review <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  Date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  ProductRating <- scrapeNodes("span.a-icon-alt")[1:10]

  product2 <- data.frame(
   category = rep(Category, length(Reviewer)),
    name = ProductName,
    reviewer = Reviewer,
    review = Review,
    date = Date,
    ratings = ProductRating
  )
  
  product2
  
linkRev2 = "https://www.amazon.co.uk/Logitech-G502-Wireless-Programmable-Next-Generation/product-reviews/B07QKC4WWD/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber=2"
  
  sessionProd2 <- bow(linkRev2,
               user_agent = "For Educational Purpose")


      Reviewer2 <- scrapeNodes("span.a-profile-name")
      Reviewer2 <- Reviewer2[1:10]

      
      Review2 <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      Review2 <- Review2[1:10]

      
      Date2 <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      Date2 <- Date2[1:10]

      
      ProductRating2 <- scrapeNodes("span.a-icon-alt")
      ProductRating2 <- ProductRating2[1:10]

      
      product2 <- rbind(product2, data.frame(category = Category ,name = ProductName,
                          reviewer = Reviewer2,
                          review = Review2,
                          date = Date2,
                         ratings = ProductRating2))
      
      product2
      
      linkRev3 = "https://www.amazon.co.uk/Logitech-G502-Wireless-Programmable-Next-Generation/product-reviews/B07QKC4WWD/ref=cm_cr_getr_d_paging_btm_next_3?ie=UTF8&reviewerType=all_reviews&pageNumber=3"
  
  sessionProd3 <- bow(linkRev3,
               user_agent = "For Educational Purpose")


      
      Reviewer3 <- scrapeNodes("span.a-profile-name")
      Reviewer3 <- Reviewer3[1:10]

      
      Review3 <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      Review3 <- Review3[1:10]

      
      Date3 <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      Date3 <- Date3[1:10]

      
      ProductRating3 <- scrapeNodes("span.a-icon-alt")
       ProductRating3 <-  ProductRating3[1:10]

      
      product2 <- rbind(product2, data.frame(category = Category ,name = ProductName,
                          reviewer = Reviewer3,
                          review = Review3,
                          date = Date3,
                         ratings =  ProductRating3))
      
      product2 <- product2[1:25,]


      product2
      


```


```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product3 <- data.frame()

Category <- "GamingMouse"

linkRev1 <- "https://www.amazon.co.uk/Razer-Deathadder-Essential-Gaming-Mouse/product-reviews/B07Y693ND1/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews"


sessionProd1 <- bow(linkRev1, user_agent = "For Educational Purpose")

scrapeNodes <- function(selector) {
  nodes <- scrape(sessionProd1) %>%
    html_nodes(selector) %>%
    html_text(trim = TRUE)
  
  if (length(nodes) == 0) {
    warning("No data found for selector: ", selector)
    return(NA)
  } else {
    return(nodes)
  }
}

  ProductName <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  Reviewer <- scrapeNodes("span.a-profile-name")[1:10]
  Review <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  Date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  ProductRating <- scrapeNodes("span.a-icon-alt")[1:10]

  product3 <- data.frame(
   category = rep(Category, length(Reviewer)),
    name = ProductName,
    reviewer = Reviewer,
    review = Review,
    date = Date,
    ratings = ProductRating
  )
  
  product3
  
linkRev2 = "https://www.amazon.co.uk/Razer-Deathadder-Essential-Gaming-Mouse/product-reviews/B07Y693ND1/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber=2"
  
  sessionProd2 <- bow(linkRev2,
               user_agent = "For Educational Purpose")


      Reviewer2 <- scrapeNodes("span.a-profile-name")
      Reviewer2 <- Reviewer2[1:10]

      
      Review2 <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      Review2 <- Review2[1:10]

      
      Date2 <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      Date2 <- Date2[1:10]

      
      ProductRating2 <- scrapeNodes("span.a-icon-alt")
      ProductRating2 <- ProductRating2[1:10]

      
      product3 <- rbind(product3, data.frame(category = Category ,name = ProductName,
                          reviewer = Reviewer2,
                          review = Review2,
                          date = Date2,
                         ratings = ProductRating2))
      
      product3
      
      linkRev3 = "https://www.amazon.co.uk/Razer-Deathadder-Essential-Gaming-Mouse/product-reviews/B07Y693ND1/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber=3"
  
  sessionProd3 <- bow(linkRev3,
               user_agent = "For Educational Purpose")


      
      Reviewer3 <- scrapeNodes("span.a-profile-name")
      Reviewer3 <- Reviewer3[1:10]

      
      Review3 <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      Review3 <- Review3[1:10]

      
      Date3 <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      Date3 <- Date3[1:10]

      
      ProductRating3 <- scrapeNodes("span.a-icon-alt")
       ProductRating3 <-  ProductRating3[1:10]

      
      product3 <- rbind(product3, data.frame(category = Category ,name = ProductName,
                          reviewer = Reviewer3,
                          review = Review3,
                          date = Date3,
                         ratings =  ProductRating3))
      
      product3 <- product3[1:25,]


      product3
      



```

```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product4 <- data.frame()

Category <- "GamingMouse"

linkRev1 <- "https://www.amazon.co.uk/SteelSeries-Aerox-Wireless-Snow-Resistant/product-reviews/B0966V1GPG/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews"


sessionProd1 <- bow(linkRev1, user_agent = "For Educational Purpose")

scrapeNodes <- function(selector) {
  nodes <- scrape(sessionProd1) %>%
    html_nodes(selector) %>%
    html_text(trim = TRUE)
  
  if (length(nodes) == 0) {
    warning("No data found for selector: ", selector)
    return(NA)
  } else {
    return(nodes)
  }
}

  ProductName <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  Reviewer <- scrapeNodes("span.a-profile-name")[1:10]
  Review <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  Date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  ProductRating <- scrapeNodes("span.a-icon-alt")[1:10]

  product4 <- data.frame(
   category = rep(Category, length(Reviewer)),
    name = ProductName,
    reviewer = Reviewer,
    review = Review,
    date = Date,
    ratings = ProductRating
  )
  
  product4
  
linkRev2 = "https://www.amazon.co.uk/SteelSeries-Aerox-Wireless-Snow-Resistant/product-reviews/B0966V1GPG/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews&pageNumber=2"
  
  sessionProd2 <- bow(linkRev2,
               user_agent = "For Educational Purpose")


      Reviewer2 <- scrapeNodes("span.a-profile-name")
      Reviewer2 <- Reviewer2[1:10]

      
      Review2 <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      Review2 <- Review2[1:10]

      
      Date2 <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      Date2 <- Date2[1:10]

      
      ProductRating2 <- scrapeNodes("span.a-icon-alt")
      ProductRating2 <- ProductRating2[1:10]

      
      product4 <- rbind(product4, data.frame(category = Category ,name = ProductName,
                          reviewer = Reviewer2,
                          review = Review2,
                          date = Date2,
                         ratings = ProductRating2))
      
      product4
      
      linkRev3 = "https://www.amazon.co.uk/SteelSeries-Aerox-Wireless-Snow-Resistant/product-reviews/B0966V1GPG/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews&pageNumber=3"
  
  sessionProd3 <- bow(linkRev3,
               user_agent = "For Educational Purpose")


      
      Reviewer3 <- scrapeNodes("span.a-profile-name")
      Reviewer3 <- Reviewer3[1:10]

      
      Review3 <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      Review3 <- Review3[1:10]

      
      Date3 <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      Date3 <- Date3[1:10]

      
      ProductRating3 <- scrapeNodes("span.a-icon-alt")
       ProductRating3 <-  ProductRating3[1:10]

      
      product4 <- rbind(product4, data.frame(category = Category ,name = ProductName,
                          reviewer = Reviewer3,
                          review = Review3,
                          date = Date3,
                         ratings =  ProductRating3))
      
      product4 <- product4[1:25,]


      product4
      

```

```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product5 <- data.frame()

Category <- "GamingMouse"

linkRev1 <- "https://www.amazon.co.uk/CORSAIR-Wired-Ambidextrous-Lightweight-Gaming/product-reviews/B07RNS9HTZ/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews"


sessionProd1 <- bow(linkRev1, user_agent = "For Educational Purpose")

scrapeNodes <- function(selector) {
  nodes <- scrape(sessionProd1) %>%
    html_nodes(selector) %>%
    html_text(trim = TRUE)
  
  if (length(nodes) == 0) {
    warning("No data found for selector: ", selector)
    return(NA)
  } else {
    return(nodes)
  }
}

  ProductName <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  Reviewer <- scrapeNodes("span.a-profile-name")[1:10]
  Review <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  Date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  ProductRating <- scrapeNodes("span.a-icon-alt")[1:10]

  product5 <- data.frame(
   category = rep(Category, length(Reviewer)),
    name = ProductName,
    reviewer = Reviewer,
    review = Review,
    date = Date,
    ratings = ProductRating
  )
  
  product5
  
linkRev2 = "https://www.amazon.co.uk/CORSAIR-Wired-Ambidextrous-Lightweight-Gaming/product-reviews/B07RNS9HTZ/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews&pageNumber=2"
  
  sessionProd2 <- bow(linkRev2,
               user_agent = "For Educational Purpose")


      Reviewer2 <- scrapeNodes("span.a-profile-name")
      Reviewer2 <- Reviewer2[1:10]

      
      Review2 <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      Review2 <- Review2[1:10]

      
      Date2 <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      Date2 <- Date2[1:10]

      
      ProductRating2 <- scrapeNodes("span.a-icon-alt")
      ProductRating2 <- ProductRating2[1:10]

      
      product5 <- rbind(product5,data.frame(category = Category ,name = ProductName,
                          reviewer = Reviewer2,
                          review = Review2,
                          date = Date2,
                         ratings = ProductRating2))
      
      product5
      
      linkRev3 = "https://www.amazon.co.uk/CORSAIR-Wired-Ambidextrous-Lightweight-Gaming/product-reviews/B07RNS9HTZ/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews&pageNumber=3"
  
  sessionProd3 <- bow(linkRev3,
               user_agent = "For Educational Purpose")


      
      Reviewer3 <- scrapeNodes("span.a-profile-name")
      Reviewer3 <- Reviewer3[1:10]

      
      Review3 <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      Review3 <- Review3[1:10]

      
      Date3 <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      Date3 <- Date3[1:10]

      
      ProductRating3 <- scrapeNodes("span.a-icon-alt")
       ProductRating3 <-  ProductRating3[1:10]

      
      product5 <- rbind(product5, data.frame(category = Category ,name = ProductName,
                          reviewer = Reviewer3,
                          review = Review3,
                          date = Date3,
                         ratings =  ProductRating3))
      
      product5 <- product5[1:25,]


      product5
      


```


```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product6 <- data.frame()

Category <- "GamingMouse"

linkRev1 <- "https://www.amazon.co.uk/Acer-Nitro-Gaming-Mouse-III/product-reviews/B0BHL92SD5/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews"


sessionProd1 <- bow(linkRev1, user_agent = "For Educational Purpose")

scrapeNodes <- function(selector) {
  nodes <- scrape(sessionProd1) %>%
    html_nodes(selector) %>%
    html_text(trim = TRUE)
  
  if (length(nodes) == 0) {
    warning("No data found for selector: ", selector)
    return(NA)
  } else {
    return(nodes)
  }
}

  ProductName <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  Reviewer <- scrapeNodes("span.a-profile-name")[1:10]
  Review <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  Date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  ProductRating <- scrapeNodes("span.a-icon-alt")[1:10]

  product6 <- data.frame(
   category = rep(Category, length(Reviewer)),
    name = ProductName,
    reviewer = Reviewer,
    review = Review,
    date = Date,
    ratings = ProductRating
  )
  
  product6
  
linkRev2 = "https://www.amazon.co.uk/Acer-Nitro-Gaming-Mouse-III/product-reviews/B0BHL92SD5/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews&pageNumber=2"
  
  sessionProd2 <- bow(linkRev2,
               user_agent = "For Educational Purpose")


      Reviewer2 <- scrapeNodes("span.a-profile-name")
      Reviewer2 <- Reviewer2[1:10]

      
      Review2 <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      Review2 <- Review2[1:10]

      
      Date2 <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      Date2 <- Date2[1:10]

      
      ProductRating2 <- scrapeNodes("span.a-icon-alt")
      ProductRating2 <- ProductRating2[1:10]

      
      product6 <- rbind(product6,data.frame(category = Category ,name = ProductName,
                          reviewer = Reviewer2,
                          review = Review2,
                          date = Date2,
                         ratings = ProductRating2))
      
      product6
      
      linkRev3 = "https://www.amazon.co.uk/Acer-Nitro-Gaming-Mouse-III/product-reviews/B0BHL92SD5/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews&pageNumber=3"
  
  sessionProd3 <- bow(linkRev3,
               user_agent = "For Educational Purpose")


      
      Reviewer3 <- scrapeNodes("span.a-profile-name")
      Reviewer3 <- Reviewer3[1:10]

      
      Review3 <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      Review3 <- Review3[1:10]

      
      Date3 <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      Date3 <- Date3[1:10]

      
      ProductRating3 <- scrapeNodes("span.a-icon-alt")
       ProductRating3 <-  ProductRating3[1:10]

      
      product6 <- rbind(product6, data.frame(category = Category ,name = ProductName,
                          reviewer = Reviewer3,
                          review = Review3,
                          date = Date3,
                         ratings =  ProductRating3))
      
      product6 <- product6[1:25,]


      product6
      

```

```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product7 <- data.frame()

Category <- "GamingMouse"

linkRev1 <- "https://www.amazon.co.uk/Trust-Programmable-Advanced-Software-Multicolour/product-reviews/B0C4FTW8TS/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews"


sessionProd1 <- bow(linkRev1, user_agent = "For Educational Purpose")

scrapeNodes <- function(selector) {
  nodes <- scrape(sessionProd1) %>%
    html_nodes(selector) %>%
    html_text(trim = TRUE)
  
  if (length(nodes) == 0) {
    warning("No data found for selector: ", selector)
    return(NA)
  } else {
    return(nodes)
  }
}

  ProductName <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  Reviewer <- scrapeNodes("span.a-profile-name")[1:10]
  Review <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  Date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  ProductRating <- scrapeNodes("span.a-icon-alt")[1:10]

  product7 <- data.frame(
   category = rep(Category, length(Reviewer)),
    name = ProductName,
    reviewer = Reviewer,
    review = Review,
    date = Date,
    ratings = ProductRating
  )
  
  product7
  
linkRev2 = "https://www.amazon.co.uk/Trust-Programmable-Advanced-Software-Multicolour/product-reviews/B0C4FTW8TS/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews&pageNumber=2"
  
  sessionProd2 <- bow(linkRev2,
               user_agent = "For Educational Purpose")


      Reviewer2 <- scrapeNodes("span.a-profile-name")
      Reviewer2 <- Reviewer2[1:10]

      
      Review2 <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      Review2 <- Review2[1:10]

      
      Date2 <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      Date2 <- Date2[1:10]

      
      ProductRating2 <- scrapeNodes("span.a-icon-alt")
      ProductRating2 <- ProductRating2[1:10]

      
      product7 <- rbind(product7,data.frame(category = Category ,name = ProductName,
                          reviewer = Reviewer2,
                          review = Review2,
                          date = Date2,
                         ratings = ProductRating2))
      
      product7
      
      linkRev3 = "https://www.amazon.co.uk/Trust-Programmable-Advanced-Software-Multicolour/product-reviews/B0C4FTW8TS/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews&pageNumber=3"
  
  sessionProd3 <- bow(linkRev3,
               user_agent = "For Educational Purpose")


      
      Reviewer3 <- scrapeNodes("span.a-profile-name")
      Reviewer3 <- Reviewer3[1:10]

      
      Review3 <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      Review3 <- Review3[1:10]

      
      Date3 <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      Date3 <- Date3[1:10]

      
      ProductRating3 <- scrapeNodes("span.a-icon-alt")
       ProductRating3 <-  ProductRating3[1:10]

      
      product7 <- rbind(product7,data.frame(category = Category ,name = ProductName,
                          reviewer = Reviewer3,
                          review = Review3,
                          date = Date3,
                         ratings =  ProductRating3))
      
      product7<- product7 [1:25,]


      product7
      


```

```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product8 <- data.frame()

Category <- "GamingMouse"

linkRev1 <- "https://www.amazon.co.uk/Roccat-Optical-Lighting-Programmable-Illumination/product-reviews/B07YCFZJN4/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews"


sessionProd1 <- bow(linkRev1, user_agent = "For Educational Purpose")

scrapeNodes <- function(selector) {
  nodes <- scrape(sessionProd1) %>%
    html_nodes(selector) %>%
    html_text(trim = TRUE)
  
  if (length(nodes) == 0) {
    warning("No data found for selector: ", selector)
    return(NA)
  } else {
    return(nodes)
  }
}

  ProductName <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  Reviewer <- scrapeNodes("span.a-profile-name")[1:10]
  Review <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  Date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  ProductRating <- scrapeNodes("span.a-icon-alt")[1:10]

  product8 <- data.frame(
   category = rep(Category, length(Reviewer)),
    name = ProductName,
    reviewer = Reviewer,
    review = Review,
    date = Date,
    ratings = ProductRating
  )
  
  product8
  
linkRev2 = "https://www.amazon.co.uk/Roccat-Optical-Lighting-Programmable-Illumination/product-reviews/B07YCFZJN4/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews&pageNumber=2"
  
  sessionProd2 <- bow(linkRev2,
               user_agent = "For Educational Purpose")


      Reviewer2 <- scrapeNodes("span.a-profile-name")
      Reviewer2 <- Reviewer2[1:10]

      
      Review2 <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      Review2 <- Review2[1:10]

      
      Date2 <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      Date2 <- Date2[1:10]

      
      ProductRating2 <- scrapeNodes("span.a-icon-alt")
      ProductRating2 <- ProductRating2[1:10]

      
      product8 <- rbind(product8,data.frame(category = Category ,name = ProductName,
                          reviewer = Reviewer2,
                          review = Review2,
                          date = Date2,
                         ratings = ProductRating2))
      
      product8
      
      linkRev3 = "https://www.amazon.co.uk/Roccat-Optical-Lighting-Programmable-Illumination/product-reviews/B07YCFZJN4/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews&pageNumber=3"
  
  sessionProd3 <- bow(linkRev3,
               user_agent = "For Educational Purpose")


      
      Reviewer3 <- scrapeNodes("span.a-profile-name")
      Reviewer3 <- Reviewer3[1:10]

      
      Review3 <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      Review3 <- Review3[1:10]

      
      Date3 <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      Date3 <- Date3[1:10]

      
      ProductRating3 <- scrapeNodes("span.a-icon-alt")
       ProductRating3 <-  ProductRating3[1:10]

      
      product8 <- rbind(product8,data.frame(category = Category ,name = ProductName,
                          reviewer = Reviewer3,
                          review = Review3,
                          date = Date3,
                         ratings =  ProductRating3))
      
      product8<- product8 [1:25,]


      product8
      


```

```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product9 <- data.frame()

Category <- "GamingMouse"

linkRev1 <- "https://www.amazon.co.uk/Xtrfy-Modular-Ultra-Light-Gaming-M42-RGB-BLUE/product-reviews/B08VRDBY67/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews"


sessionProd1 <- bow(linkRev1, user_agent = "For Educational Purpose")

scrapeNodes <- function(selector) {
  nodes <- scrape(sessionProd1) %>%
    html_nodes(selector) %>%
    html_text(trim = TRUE)
  
  if (length(nodes) == 0) {
    warning("No data found for selector: ", selector)
    return(NA)
  } else {
    return(nodes)
  }
}

  ProductName <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  Reviewer <- scrapeNodes("span.a-profile-name")[1:10]
  Review <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  Date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  ProductRating <- scrapeNodes("span.a-icon-alt")[1:10]

  product9 <- data.frame(
   category = rep(Category, length(Reviewer)),
    name = ProductName,
    reviewer = Reviewer,
    review = Review,
    date = Date,
    ratings = ProductRating
  )
  
  product9
  
linkRev2 = "https://www.amazon.co.uk/Xtrfy-Modular-Ultra-Light-Gaming-M42-RGB-BLUE/product-reviews/B08VRDBY67/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews&pageNumber=2"
  
  sessionProd2 <- bow(linkRev2,
               user_agent = "For Educational Purpose")


      Reviewer2 <- scrapeNodes("span.a-profile-name")
      Reviewer2 <- Reviewer2[1:10]

      
      Review2 <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      Review2 <- Review2[1:10]

      
      Date2 <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      Date2 <- Date2[1:10]

      
      ProductRating2 <- scrapeNodes("span.a-icon-alt")
      ProductRating2 <- ProductRating2[1:10]

      
      product9<- rbind(product9,data.frame(category = Category ,name = ProductName,
                          reviewer = Reviewer2,
                          review = Review2,
                          date = Date2,
                         ratings = ProductRating2))
      
      product9
      
      linkRev3 = "https://www.amazon.co.uk/Xtrfy-Modular-Ultra-Light-Gaming-M42-RGB-BLUE/product-reviews/B08VRDBY67/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews&pageNumber=3"
  
  sessionProd3 <- bow(linkRev3,
               user_agent = "For Educational Purpose")


      
      Reviewer3 <- scrapeNodes("span.a-profile-name")
      Reviewer3 <- Reviewer3[1:10]

      
      Review3 <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      Review3 <- Review3[1:10]

      
      Date3 <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      Date3 <- Date3[1:10]

      
      ProductRating3 <- scrapeNodes("span.a-icon-alt")
       ProductRating3 <-  ProductRating3[1:10]

      
      product9 <- rbind(product9,data.frame(category = Category ,name = ProductName,
                          reviewer = Reviewer3,
                          review = Review3,
                          date = Date3,
                         ratings =  ProductRating3))
      
      product9<- product9 [1:25,]


      product9
      


```

```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product10 <- data.frame()

Category <- "GamingMouse"

linkRev1 <- "https://www.amazon.co.uk/Oversteel-RADIUM-Gaming-Programmable-Buttons/product-reviews/B083SYB56X/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews"


sessionProd1 <- bow(linkRev1, user_agent = "For Educational Purpose")

scrapeNodes <- function(selector) {
  nodes <- scrape(sessionProd1) %>%
    html_nodes(selector) %>%
    html_text(trim = TRUE)
  
  if (length(nodes) == 0) {
    warning("No data found for selector: ", selector)
    return(NA)
  } else {
    return(nodes)
  }
}

  ProductName <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  Reviewer <- scrapeNodes("span.a-profile-name")[1:10]
  Review <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  Date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  ProductRating <- scrapeNodes("span.a-icon-alt")[1:10]

  product10 <- data.frame(
   category = rep(Category, length(Reviewer)),
    name = ProductName,
    reviewer = Reviewer,
    review = Review,
    date = Date,
    ratings = ProductRating
  )
  
  product10
  
linkRev2 = "https://www.amazon.co.uk/Oversteel-RADIUM-Gaming-Programmable-Buttons/product-reviews/B083SYB56X/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews&pageNumber=2"
  
  sessionProd2 <- bow(linkRev2,
               user_agent = "For Educational Purpose")


      Reviewer2 <- scrapeNodes("span.a-profile-name")
      Reviewer2 <- Reviewer2[1:10]

      
      Review2 <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      Review2 <- Review2[1:10]

      
      Date2 <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      Date2 <- Date2[1:10]

      
      ProductRating2 <- scrapeNodes("span.a-icon-alt")
      ProductRating2 <- ProductRating2[1:10]

      
      product10<- rbind(product10,data.frame(category = Category ,name = ProductName,
                          reviewer = Reviewer2,
                          review = Review2,
                          date = Date2,
                         ratings = ProductRating2))
      
      product10
      
      linkRev3 = "https://www.amazon.co.uk/Oversteel-RADIUM-Gaming-Programmable-Buttons/product-reviews/B083SYB56X/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews&pageNumber=3"
  
  sessionProd3 <- bow(linkRev3,
               user_agent = "For Educational Purpose")


      
      Reviewer3 <- scrapeNodes("span.a-profile-name")
      Reviewer3 <- Reviewer3[1:10]

      
      Review3 <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      Review3 <- Review3[1:10]

      
      Date3 <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      Date3 <- Date3[1:10]

      
      ProductRating3 <- scrapeNodes("span.a-icon-alt")
       ProductRating3 <-  ProductRating3[1:10]

      
      product10<- rbind(product10,data.frame(category = Category ,name = ProductName,
                          reviewer = Reviewer3,
                          review = Review3,
                          date = Date3,
                         ratings =  ProductRating3))
      
      product10<- product10 [1:25,]


      product10
      

```


##############################################################################################


CSV FILE
```{r}

all_product <- rbind(product1,product2,product3,product4,product5,product6,product7,product8,product9,product10)

all_product

write.csv(all_product,"10Products.csv")


```

```{r}
library(DBI)
library(odbc)
library(RMySQL)
library(dplyr,dbplyr)
connection <- dbConnect(RMySQL::MySQL(),
                        dsn="MariaDB-connection",
                        Server = "localhost",
                        dbname = "huervanalab1db", 
                        user = "root", 
                        password = "") 

```

```{r}

#install.packages("readr")
library(readr)

monitor <- read.csv("GAMING ACCESSORIES-MONITOR.csv")
tail(monitor)

mouse <- read.csv("GAMING ACCESSORIES-MOUSE.csv")
tail(mouse)

tenProd <- read.csv("10Products.csv")
tail(tenProd)

```

```{r}

dbWriteTable(connection, 'lab1Monitor', monitor, append = TRUE)
dbWriteTable(connection, 'lab1Mouse', mouse, append = TRUE)
dbWriteTable(connection, 'lab1tenProd', tenProd, append = TRUE)

```


```{r}
dbListTables(connection)
dbListFields(connection,"lab1Monitor")
dbListFields(connection,"lab1Mouse")
dbListFields(connection,"lab1tenProd")
```

```{r}

review_data <- dbGetQuery(connection, "SELECT * FROM huervanalab1db.lab1Monitor")
glimpse(review_data)


review_data2 <- dbGetQuery(connection, "SELECT * FROM huervanalab1db.lab1Mouse")
glimpse(review_data)

review_data2 <- dbGetQuery(connection, "SELECT * FROM huervanalab1db.lab1tenProd")
glimpse(review_data)

```
