---
title: "Practical Exam"
output:
  pdf_document: default
  html_document:
    df_print: paged
date: "2024-02-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


A. Load the built-in warpbreaks dataset.
```{r}
#1.Find out, in a single command, which columns of warpbreaks are either numeric or integer. What are the data types of each column?
  
data(warpbreaks)
warpbreaks

sapply(warpbreaks, class)


```

```{r}

#2.How many observations does it have?
nrow(warpbreaks)

# The number of observations the data set have is 54.

```

```{r}
#3.Is numeric a natural data type for the columns which are stored as such? Convert to integer when necessary.

numeric <-as.integer(warpbreaks$breaks)
class(warpbreaks$breaks)


```

```{r}
#4Explain what is the error all about. Do not just copy the error message that was displayed.

# I did not counter an error withg my previous codes.

```


B.Load the exampleFile.txt


```{r}


#1.Read the complete file using readLines.
ReadExample <- readLines("exampleFile.txt")
ReadExample


```

```{r}
#2 Separate the vector of lines into a vector containing comments and a vector containing the data. Hint: use grepl.

ReadExample <- readLines("exampleFile.txt")


comment_lines <- grepl("^#", ReadExample)

comments <- ReadExample[comment_lines]
data <- ReadExample[!comment_lines]

data
```


```{r}
#3 Extract the date from the first comment line and display on the screen “It was created data.”

ReadExample <- readLines("exampleFile.txt")
firstLine <- ReadExample[1]
dateString <- gsub("Created : (\\d{2} [A-Za-z]+ \\d{4})", "\\1", firstLine)
cat("It was created", dateString, ".\n")

```


```{r}
#4 Read the data into a matrix as follows.

#a. Split the character vectors in the vector containing data lines by semicolon (;) using strsplit.
splitmtrx <- lapply(data, function(line) unlist(strsplit(line, split = ";")))
splitmtrx

```

```{r}
#b.Find the maximum number of fields retrieved by split. Append rows that are shorter with NA's.

max <- max(sapply(splitmtrx, length))
max

withNA <- lapply(splitmtrx, function(line) {
  line_with_na <- c(line, rep(NA, max - length(line)))
  return(line_with_na)
})

withNA

```

```{r}
#c. Use unlist and matrix to transform the data to row-column format.

rowcol <- matrix(unlist(withNA), nrow = max, byrow = TRUE)

rowcol

```

```{r}
#d.From comment lines 2-4, extract the names of the fields. Set these as colnames for the matrix you just created.

#ReadExample <- readLines("exampleFile.txt")

#comment_lines <- grepl("^#", ReadExample)
#comments <- ReadExample[comment_lines]
#data <- ReadExample[!comment_lines]

#data <- matrix(unlist(strsplit(data, split = ";")), nrow = max(sapply(strsplit(data, split = ";"), #length)))
#colnames(data) <- gsub("^#", "", comments[2:4])

#ERROR : Error in dimnames(x) <- dn :  length of 'dimnames' [2] not equal to array extent

```




