---
title: "Lab Exercise 2"
output: html_document
date: "2024-02-15"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}


library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product1 <- data.frame()

for (page in 1:5) {
  link1 <- paste0("https://www.amazon.com.au/HCE-Hex-Dumbbells-Set-Bodybuilding/product-reviews/B0BHW38XXX/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session1 <- bow(link1, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session1) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "HCE Hex Dumbbells Set - Rubber Coated Dumbbells Black Hex Dumbbell Weights"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product1 <- rbind(product1, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  #Sys.sleep(3)
}

#View(product1)

```

```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product2 <- data.frame()

for (page in 1:5) {
  link2 <- paste0("https://www.amazon.com.au/SERTT-Weight-Upgraded-Attachments-Workouts/product-reviews/B095NZKSP2/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session2 <- bow(link2, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session2) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "HSERTT Weight Cable Pulley System Gym"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product2 <- rbind(product2, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  #Sys.sleep(3)
}

#View(product2)

```


```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product3 <- data.frame()

for (page in 1:5) {
  link3 <- paste0("https://www.amazon.com.au/CKDCARES-Roller-Abdominal-Workout-Equipment/product-reviews/B0918NNB1S/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session3 <- bow(link3, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session3) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "CKDCARES Ab Wheel Roller with Knee Pad Abdominal Workout Equipment for Home Gym"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product3 <- rbind(product3, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

 # Sys.sleep(3)
}

#View(product3)


```

```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product4 <- data.frame()

for (page in 1:5) {
  link4 <- paste0("https://www.amazon.com.au/PROIRON-Resistance-Bands-Assisted-Powerlifting/product-reviews/B07P8JSGLF/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session4 <- bow(link4, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session4) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "PROIRON Pull Up Bands Heavy Duty Resistance Band"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product4 <- rbind(product4, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  #Sys.sleep(3)
}

#View(product4)

```


```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product5 <- data.frame()

for (page in 1:5) {
  link5 <- paste0("https://www.amazon.com.au/Fat-Gripz-Pro-Forearms-Magazine/product-reviews/B07QKML1SL/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session5 <- bow(link5, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session5) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Fat Gripz Pro"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product5 <- rbind(product5, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  #Sys.sleep(3)
}

#View(product5)

```

```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product6 <- data.frame()

for (page in 1:5) {
  link6 <- paste0("https://www.amazon.com.au/Olympic-Barbell-Weightlifting-Dumbbell-Straight/product-reviews/B07B46MPYT/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session6 <- bow(link6, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session6) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "METEOR Olympic Barbell"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product6 <- rbind(product6, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  #Sys.sleep(3)
}

#View(product6)

```

```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product7 <- data.frame()

for (page in 1:5) {
  link7 <- paste0("https://www.amazon.com.au/Olympic-Barbell-Weightlifting-Dumbbell-Straight/product-reviews/B07B46MPYT/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session7 <- bow(link7, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session7) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "METEOR Olympic Barbell"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product7 <- rbind(product7, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  #Sys.sleep(3)
}

#View(product7)


```


```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product8 <- data.frame()

for (page in 1:5) {
  link8 <- paste0("https://www.amazon.com.au/Prosource-Ultimate-Connector-Unisex-Adult-ps-1064-ds-black/product-reviews/B07BHWFH1W/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session8 <- bow(link8, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session8) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Prosource Fit Dip Stand Station"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product8 <- rbind(product8, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  #Sys.sleep(3)
}

#View(product8)


```


```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product9 <- data.frame()

for (page in 1:5) {
  link9 <- paste0("https://www.amazon.com.au/Sunny-Health-Fitness-Unisexs-SF-S020027/product-reviews/B08NFHFNXV/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session9 <- bow(link9, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session9) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Sunny Health & Fitness Twisting Stair Stepper Machine"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product9 <- rbind(product9, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  #Sys.sleep(3)
}

#View(product9)

```


```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product10 <- data.frame()

for (page in 1:5) {
  link10 <- paste0("https://www.amazon.com.au/1-SIZE-Iron-Gym/product-reviews/B001EJMS6K/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session10 <- bow(link10, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session10) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Iron Gym Pull Up Bars"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product10 <- rbind(product10, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  #Sys.sleep(3)
}

#View(product10)

```


```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product11 <- data.frame()

for (page in 1:5) {
  link11 <- paste0("https://www.amazon.com.au/INNOCEDAR-Resistance-60-180LBS-Adjustable-Equipment/product-reviews/B08NYBZLNM/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session11 <- bow(link11, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session11) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "INNOCEDAR Home Gym Bar Kit with Resistance Bands"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product11 <- rbind(product11, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  #Sys.sleep(3)
}

#View(product11)

```


```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product12 <- data.frame()

for (page in 1:5) {
  link12 <- paste0("https://www.amazon.com.au/HCE-Barbell-Dumbbell-Weight-Plates/product-reviews/B079YTXZFY/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session12 <- bow(link12, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session12) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "HCE Hex Barbell Weights"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product12 <- rbind(product12, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

 #Sys.sleep(3)
}

#View(product12)


```


```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product13 <- data.frame()

for (page in 1:5) {
  link13 <- paste0("https://www.amazon.com.au/LALAHIGH-Equipment-Upgraded-Foldable-Resistance/product-reviews/B0B3487C5T/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session13 <- bow(link13, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session13) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "LALAHIGH Push Up Board"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product13 <- rbind(product13, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  #Sys.sleep(3)
}

#View(product13)

```


```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product14 <- data.frame()

for (page in 1:5) {
  link14 <- paste0("https://www.amazon.com.au/Adjustable-Hammertone-Dumbbell-Strength-Equipment/product-reviews/B079P35XZY/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session14 <- bow(link14, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session14) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "HCE Adjustable Dumbbells Set"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product14 <- rbind(product14, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  #Sys.sleep(3)
}

#View(product14)

```


```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product15 <- data.frame()

for (page in 1:5) {
  link15 <- paste0("https://www.amazon.com.au/Resistance-Extenseurs-Résistance-Musculation-Rééducation/product-reviews/B078XCK6SF/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session15 <- bow(link15, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session15) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Resistance Bands Set of 5 with Handle Strength Exercise Resistance Band"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product15 <- rbind(product15, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  #Sys.sleep(3)
}

#View(product15)

```

```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product16 <- data.frame()

for (page in 1:5) {
  link16 <- paste0("https://www.amazon.com.au/HCE-Standard-Weight-Dumbbell-Barbell/product-reviews/B079YX1X5C/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session16 <- bow(link16, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session16) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "HCE Standard Rubbercoated Weight Plate for Dumbbell and Barbell"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product16 <- rbind(product16, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  #Sys.sleep(3)
}

#View(product16)

```


```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product17 <- data.frame()

for (page in 1:5) {
  link17 <- paste0("https://www.amazon.com.au/HCE-Stackable-Organiser-Heavy-Duty-Commercial/product-reviews/B079WYLW5M/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session17 <- bow(link17, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session17) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "HCE Vertical Olympic Bumper Plate Rack with Wheels"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product17 <- rbind(product17, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  #Sys.sleep(3)
}

#View(product17)


```


```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product18 <- data.frame()

for (page in 1:5) {
  link18 <- paste0("https://www.amazon.com.au/Resistance-Working-Exercise-Assistance-Equipment/product-reviews/B0BTRTPNY4/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session18 <- bow(link18, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session18) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "VEICK Resistance Bands for Working Out"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product18 <- rbind(product18, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  #Sys.sleep(3)
}

#View(product18)

```


```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product19 <- data.frame()

for (page in 1:5) {
  link19 <- paste0("https://www.amazon.com.au/EZ-Curl-Bar-Training-Accessory/product-reviews/B079K179XP/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session19 <- bow(link19, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session19) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "EZ Curl Bar - Heavy Weight Training Accessory Designed for Total Gym"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product19 <- rbind(product19, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

 # Sys.sleep(3)
}

#View(product19)


```

```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product20 <- data.frame()

for (page in 1:5) {
  link20 <- paste0("https://www.amazon.com.au/BCBIG-Dumbbells-Adjustable-Dumbbell-Aerobics/product-reviews/B096G2G2KV/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session20 <- bow(link20, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session20) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "BCBIG Dumbbells Set"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product20 <- rbind(product20, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

 #Sys.sleep(3)
}

#View(product20)

```

```{r}


library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product21 <- data.frame()

for (page in 1:5) {
  link21 <- paste0("https://www.amazon.com.au/Apex-Adjustable-Heavy-Duty-Exercise-Kettlebell/product-reviews/B074N5392C/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session21 <- bow(link21, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session21) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Apex Adjustable Heavy-Duty Exercise Kettlebell"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product21 <- rbind(product21, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

 #Sys.sleep(3)
}

#View(product21)


```

```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product22 <- data.frame()

for (page in 1:5) {
  link22 <- paste0("https://www.amazon.com.au/Vulken-Attachment-Extra-Long-Equipment-Resistance/product-reviews/B085RM28R7/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session22 <- bow(link22, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session22) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Vulken Tricep Rope Cable Attachment"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product22 <- rbind(product22, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

 #Sys.sleep(3)
}

#View(product22)

```

```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product23 <- data.frame()

for (page in 1:5) {
  link23 <- paste0("https://www.amazon.com.au/Yes4All-Interlocking-Exercise-Equipment-Square/product-reviews/B0716SW4WP/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session23 <- bow(link23, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session23) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Yes4All Interlocking Exercise Foam Mats"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product23 <- rbind(product23, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

 #Sys.sleep(3)
}

#View(product23)


```

```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product24 <- data.frame()

for (page in 1:5) {
  link24 <- paste0("https://www.amazon.com.au/Portable-Squat-Fitness-Exercise-Equipment/product-reviews/B079MDQC3Y/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session24 <- bow(link24, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session24) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "HCE Pair of Adjustable Barbell Squat Rack Stand"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product24 <- rbind(product24, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

 #Sys.sleep(3)
}

#View(product24)

```

```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product25 <- data.frame()

for (page in 1:5) {
  link25 <- paste0("https://www.amazon.com.au/Storage-Equipment-Dumbbell-Resistance-Kettlebell/product-reviews/B0CNV8J5FF/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session25 <- bow(link25, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session25) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Yoga Mat Storage Gym Equipment Dumbbell Stand Dumbbell Rack"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product25 <- rbind(product25, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

 #Sys.sleep(3)
}

#View(product25)

```

```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product26 <- data.frame()

for (page in 1:5) {
  link26 <- paste0("https://www.amazon.com.au/Daisy-Chain-Dip-Belt-Weight/product-reviews/B0CHYB2FD6/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session26 <- bow(link26, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session26) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Daisy Chain for Dip Belt & Weight Belt"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product26 <- rbind(product26, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

 #Sys.sleep(3)
}

#View(product26)

```

```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product27 <- data.frame()

for (page in 1:5) {
  link27 <- paste0("https://www.amazon.com.au/Adjustable-Barbell-Dumbbell-Weight-Fitness/product-reviews/B078WZRXJR/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session27 <- bow(link27, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session27) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "HCE 50kg Adjustable Hammertone Barbell & Dumbbell Set Pro"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product27 <- rbind(product27, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

 #Sys.sleep(3)
}

#View(product27)

```


```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product28 <- data.frame()

for (page in 1:5) {
  link28 <- paste0("https://www.amazon.com.au/Vinmooog-Strength-Equipment-Adjustable-Resistance/product-reviews/B0C8SG9JFT/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session28 <- bow(link28, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session28) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Vinmooog Hand Trainer Finger Trainer Forearm Trainer Fitness"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product28 <- rbind(product28, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

 #Sys.sleep(3)
}

#View(product28)

```

```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product29 <- data.frame()

for (page in 1:5) {
  link29 <- paste0("https://www.amazon.com.au/CDCASA-Dumbbells-Adjustable-Exercise-Connecting/product-reviews/B08F1V4PNJ/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session29 <- bow(link29, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session29) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "CDCASA Adjustable Dumbbells, 44 or 66 Lbs Weight Set"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product29 <- rbind(product29, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

 #Sys.sleep(3)
}

#View(product29)
```

```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product30 <- data.frame()

for (page in 1:5) {
  link30 <- paste0("https://www.amazon.com.au/PORTENTUM-Strength-Training-Different-Multi-Colour/product-reviews/B0BR8JHGSP/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session30 <- bow(link30, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session30) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Resistance Bands Widerstandsbänder"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product30 <- rbind(product30, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

 #Sys.sleep(3)
}

#View(product30)

```

```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product31 <- data.frame()

for (page in 1:5) {
  link31 <- paste0("https://www.amazon.com.au/DMoose-Fitness-Weightlifting-Neoprene-Belts/product-reviews/B08WWP57FM/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session31 <- bow(link31, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session31) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "DMoose Weight Lifting Belt - Lifting Belt with Self-Lock System"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product31 <- rbind(product31, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

 #Sys.sleep(3)
}

#View(product31)

```


```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product32 <- data.frame()

for (page in 1:5) {
  link32 <- paste0("https://www.amazon.com.au/Black-Yes4All-Lifting-Shoulder-Protective/product-reviews/B013JOAWMY/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session32 <- bow(link32, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session32) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Yes4All Barbell Foam Bar Pad - Barbell Squat Pad"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product32 <- rbind(product32, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

 #Sys.sleep(3)
}

#View(product32)

```

```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product33 <- data.frame()

for (page in 1:5) {
  link33 <- paste0("https://www.amazon.com.au/GYM-PEOPLE-Women-Tummy-Control-Athletic/product-reviews/B07QN3W3BY/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session33 <- bow(link33, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session33) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "THE GYM PEOPLE High Waist Yoga Shorts for Women's"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product33 <- rbind(product33, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

 #Sys.sleep(3)
}

#View(product33)

```

```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product34 <- data.frame()

for (page in 1:5) {
  link34 <- paste0("https://www.amazon.com.au/Thickened-Workout-Multi-Grip-Strength-Portable/product-reviews/B08MY13HYC/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session34 <- bow(link34, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session34) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Ally Peaks Pull Up Bar for Doorway"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product34 <- rbind(product34, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

  #Sys.sleep(3)
}

#View(product34)

```

```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product35 <- data.frame()

for (page in 1:5) {
  link35 <- paste0("https://www.amazon.com.au/Arena-Resistance-Non-Slip-Stretch-Warranty/product-reviews/B07D7KX9PX/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session35 <- bow(link35, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session35) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Arena Strength Booty Fabric Bands"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product35 <- rbind(product35, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

 #Sys.sleep(3)
}

#View(product35)

```

```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product36 <- data.frame()

for (page in 1:5) {
  link36 <- paste0("https://www.amazon.com.au/Yes4All-Vinyl-Coated-Kettlebells-Available/product-reviews/B085Q3SYKW/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session36 <- bow(link36, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session36) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Yes4All Kettlebells with Protective Rubber Base"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product36 <- rbind(product36, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

 #Sys.sleep(3)
}

#View(product36)

```

```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product37 <- data.frame()

for (page in 1:5) {
  link37 <- paste0("https://www.amazon.com.au/Hawk-Fitness-Dipping-Training-Bodybuilding/product-reviews/B01MFAWSW8/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session37 <- bow(link37, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session37) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Hawk Fitness Dip Belt with Chain"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product37 <- rbind(product37, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

 #Sys.sleep(3)
}

#View(product37)

```

```{r}


library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product38 <- data.frame()

for (page in 1:5) {
  link38 <- paste0("https://www.amazon.com.au/RitFit-Barbell-Squat-Pad-Black/product-reviews/B071XSRMQ9/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session38 <- bow(link38, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session38) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "RitFit Barbell Squat Pad, Advanced Neck & Shoulder Ergonomic Protective Pad"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product38 <- rbind(product38, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

 #Sys.sleep(3)
}

#View(product38)

```

```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product39 <- data.frame()

for (page in 1:5) {
  link39 <- paste0("https://www.amazon.com.au/SPRI-SC-2R-Braided-Xertube-Level/product-reviews/B003TKSTLA/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session39 <- bow(link39, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session39) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "SPRI Braided Xertube Resistance Bands"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product39<- rbind(product39, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

 #Sys.sleep(3)
}

#View(product39)

```

```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product40 <- data.frame()

for (page in 1:5) {
  link40 <- paste0("https://www.amazon.com.au/Golds-Gym-Original-Strength-Intensive/product-reviews/B08ND667Y8/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session40 <- bow(link40, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session40) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Gold`s Gym 3710 Power Grip Pro,"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product40 <- rbind(product40, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

 #Sys.sleep(3)
}

#View(product40)
```

```{r}


library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product41 <- data.frame()

for (page in 1:5) {
  link41 <- paste0("https://www.amazon.com.au/NewMe-Fitness-Kettlebell-Threaded-Handle/product-reviews/B07NDLBHMS/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session41 <- bow(link41, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session41) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "NewMe Fitness Adjustable Kettlebell Handle for Use with Weight Plates"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product41 <- rbind(product41, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

 #Sys.sleep(3)
}

#View(product41)

```

```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product42 <- data.frame()

for (page in 1:5) {
  link42 <- paste0("https://www.amazon.com.au/Building-Restriction-Occlusion-Workouts-Resistance/product-reviews/B08RCXTQXQ/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session42 <- bow(link42, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session42) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "BFR Booty Bands for Women"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product42 <- rbind(product42, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

 #Sys.sleep(3)
}

#View(product42)

```


```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product43 <- data.frame()

for (page in 1:5) {
  link43 <- paste0("https://www.amazon.com.au/Under-Armour-HeatGear-1361596-090-Heather/product-reviews/B0874WWX2P/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session43 <- bow(link43, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session43) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Under Armour Men's Armour HeatGear Compression Shorts"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product43 <- rbind(product43, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

 #Sys.sleep(3)
}

#View(product43)

```

```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product44 <- data.frame()

for (page in 1:5) {
  link44 <- paste0("https://www.amazon.com.au/Amonax-Convertible-Exercise-Strength-Training/product-reviews/B081Z7BBMB/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session44 <- bow(link44, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session44) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Amonax Convertible Ab Wheel Roller"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product44 <- rbind(product44, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

 #Sys.sleep(3)
}

#View(product44)

```

```{r}


library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product45 <- data.frame()

for (page in 1:5) {
  link45 <- paste0("https://www.amazon.com.au/Pilates-Kit-Resistance-Bands-Bar/product-reviews/B089M43MZ6/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session45 <- bow(link45, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session45) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "MALOOW Portable Pilates Exercise Bar Kit with Adjustable Resistance Bands"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product45 <- rbind(product45, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

 #Sys.sleep(3)
}

#View(product45)

```

```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product46 <- data.frame()

for (page in 1:5) {
  link46 <- paste0("https://www.amazon.com.au/LifelineUSA-LLJGXT-XT-Jungle-Gym/product-reviews/B004R3VQU4/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session46 <- bow(link46, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session46) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Lifeline Jungle Gym Suspension Trainer"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product46 <- rbind(product46, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

 #Sys.sleep(3)
}

#View(product46)


```


```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product47 <- data.frame()

for (page in 1:5) {
  link47 <- paste0("https://www.amazon.com.au/BalanceFrom-Trainer-Abdominal-Exercise-Exerciser/product-reviews/B07TTVC6QH/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session47 <- bow(link47, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session47) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "BalanceFrom Ab Mat Trainer Abdominal Machine"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product47 <- rbind(product47, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

 #Sys.sleep(3)
}

#View(product47)

```

```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product48 <- data.frame()

for (page in 1:5) {
  link48 <- paste0("https://www.amazon.com.au/Yes4All-Exercise-Tailbone-Protecting-Abdominal/product-reviews/B073VCMBSZ/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session48 <- bow(link48, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session48) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Yes4All Ab Exercise Mat with Tailbone Protecting Pad"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product48 <- rbind(product48, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

 #Sys.sleep(3)
}

#View(product48)

```

```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product49 <- data.frame()

for (page in 1:5) {
  link49 <- paste0("https://www.amazon.com.au/Yes4All-1-inch-Weight-Plates-Dumbbells/product-reviews/B00IHM82VW/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session49 <- bow(link49, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session49) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Yes4All-1-inch-Weight-Plates-Dumbbells"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product49 <- rbind(product49, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

 #Sys.sleep(3)
}

#View(product49)

```

```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product50 <- data.frame()

for (page in 1:5) {
  link50 <- paste0("https://www.amazon.com.au/Neoprene-Dumbbell-Weights-Anti-Slip-Anti-roll/product-reviews/B087JDLWLQ/ref=cm_cr_dp_d_show_all_btm_next_", page, "?ie=UTF8&reviewerType=all_reviews&pageNumber=", page)
  session50 <- bow(link50, user_agent = "Educational Purpose")

  scrapeNodes <- function(selector) {
    scrape(session50) %>%
      html_nodes(selector) %>%
      html_text(trim = TRUE)
  }

  productName <- "Portzon 8 Colors Options Compatible with Set of 2 Rubber Dumbbell"
  scrapedTitle <- scrapeNodes("span.a-size-base.review-title.a-color-base.review-title-content.a-text-bold")[1:10]
  scrapedReviewer <- scrapeNodes("span.a-profile-name")[1:10]
  scrapedReview <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  scrapedDate <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  scrapedRating <- scrapeNodes("span.a-icon-alt")[1:10]
  scrapedType <- scrapeNodes("span.a-size-mini.a-color-state.a-text-bold")[1:10]

  product50 <- rbind(product50, data.frame(
    prod_name = productName,
    title = scrapedTitle,
    reviewer = scrapedReviewer,
    review = scrapedReview,
    date = scrapedDate,
    ratings = scrapedRating,
    type_of_purchase = scrapedType
  ))

 #Sys.sleep(3)
}

#View(product50)


```